allmake: defines.h io.h io.cpp graph.h graph.cpp prim.h prim.cpp inspect.h inspect.cpp heuristic.h heuristic.cpp subgradient.h subgradient.cpp  preprocess.h preprocess.cpp ch.h ch.cpp main.cpp
	g++ io.cpp graph.cpp prim.cpp inspect.cpp heuristic.cpp subgradient.cpp preprocess.cpp ch.cpp main.cpp -o relaxlag -Wall -O2 -lm -std=c++11
