allmake: defines.h io.h io.cpp graph.h graph.cpp prim.h prim.cpp inspect.h inspect.cpp heuristic.h heuristic.cpp subgradient.h subgradient.cpp main.cpp
	g++ io.cpp graph.cpp prim.cpp inspect.cpp heuristic.cpp subgradient.cpp main.cpp -o main -Wall -O2 -lm -std=c++11
